### ISSUE TITLE
script freezing than send originate failed

### ISSUE THREAD

**Issue by redjoe** [gawel/panoramisk#37] opened 2016-04-13 17:30 UTC
I face the following problem when creating originate:

When creating originate with "async: false" using manager.send_action and call fails, I receive message
`<Message ActionID='action/02eec16a-b92f-4682-a551-918df9c27b07/1/163' Message='Originate failed' Response='Error' content=''>`

When creating originate using manager.send_action with "async: true" or using callmanager.send_originate and call fails, then program freezes on line
`call = yield from callmanager.send_originate({...})`

In separate window I'm catching events OriginateResponse and see
`<Message ActionID='action/3fdcc20c-7299-479d-bf98-631a5bb7904c/1/2' CallerIDName='testcall' CallerIDNum='<unknown>' Channel='SIP/test1-01/48727xxxxxx' Context='' Event='OriginateResponse' Exten='' Privilege='call,all' Reason='5' Response='Failure' Uniqueid='<null>' content=''>`

An example of event when call is successful:
`<Message ActionID='action/8d6fa9cb-a263-4bed-b381-28b305f4df03/1/2' CallerIDName='testcall' CallerIDNum='<unknown>' Channel='Local/48727xxxxxx@amicall-00000031;1' Context='amicall' Event='OriginateResponse' Exten='48727xxxxxx' Privilege='call,all' Reason='4' Response='Success' Uniqueid='1459861026.799672' content=''>`

**Comment by sisoftrg** [comment] 2016-07-01 11:06
I can confirm this issue for version 1.0. but it looks like fixed in commit bf0dd3e43f4603af0d67c06baaa79663947ee03b. I'm applied change from the commit and testing now.

**Closed** 2016-12-29 15:26 UTC

**Comment by gawel** [comment] 2016-12-29 15:28
Should no longer be a problem since 1.1 is released
